


#pragma once

#define DXSTATUS_SUCCESS        ( ( NTSTATUS )( STATUS_SEVERITY_SUCCESS_MASK | FACILITY_DXGI_MASK | 0x00000000L ) )
#define DXSTATUS_UNSUCCESSFUL   ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_DXGI_MASK | 0x00000001L ) )
#define DXSTATUS_UNSUPPORTED    ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_DXGI_MASK | 0x00000002L ) )
