


#pragma once

#define STATUS_SEVERITY_SUCCESS                 0x0
#define STATUS_SEVERITY_INFORMATIONAL           0x1
#define STATUS_SEVERITY_WARNING                 0x2
#define STATUS_SEVERITY_ERROR                   0x3

#define STATUS_SEVERITY_SUCCESS_MASK            ( STATUS_SEVERITY_SUCCESS << 30 )
#define STATUS_SEVERITY_INFORMATIONAL_MASK      ( STATUS_SEVERITY_INFORMATIONAL << 30 )
#define STATUS_SEVERITY_WARNING_MASK            ( STATUS_SEVERITY_WARNING << 30 )
#define STATUS_SEVERITY_ERROR_MASK              ( STATUS_SEVERITY_ERROR << 30 )

#define STATUS_CUSTOMER_BIT_MASK                ( 0x20000000L )

#define NT_SUCCESS( status )                    ( ( ( status ) & STATUS_SEVERITY_ERROR_MASK ) == 0 )

#define FACILITY_SYSTEM                         0x0
#define FACILITY_DXGI                           0x1
#define FACILITY_SYSTEM_MASK                    ( ( NTSTATUS )( FACILITY_SYSTEM << 16 ) )
#define FACILITY_DXGI_MASK                      ( ( NTSTATUS )( FACILITY_DXGI << 16 ) )

#define STATUS_SUCCESS                          ( ( NTSTATUS )( STATUS_SEVERITY_SUCCESS_MASK | FACILITY_SYSTEM_MASK | 0x00000000L ) )
#define STATUS_UNSUCCESSFUL                     ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000001L ) )
#define STATUS_BUFFER_TOO_SMALL                 ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000002L ) )
#define STATUS_INVALID_PATH                     ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000003L ) )
#define STATUS_INVALID_HANDLE                   ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000004L ) )
#define STATUS_INVALID_IMAGE                    ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000005L ) )
#define STATUS_NOT_FOUND                        ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000006L ) )
#define STATUS_INVALID_THREAD                   ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000007L ) )
#define STATUS_ACCESS_DENIED                    ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000008L ) )
#define STATUS_INVALID_ATTRIBUTES               ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000009L ) )
#define STATUS_INVALID_ADDRESS                  ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000AL ) )
#define STATUS_PARTIALLY_COMPLETE               ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000BL ) )
#define STATUS_INVALID_REQUEST                  ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000CL ) )
#define STATUS_INVALID_BUFFER                   ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000DL ) )
#define STATUS_INVALID_OBJECT_TYPE              ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000EL ) )
#define STATUS_INACCESSIBLE_DEVICE              ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x0000000FL ) )
#define STATUS_ACCESS_VIOLATION                 ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000010L ) )
#define STATUS_NO_MORE_FILES                    ( ( NTSTATUS )( STATUS_SEVERITY_ERROR_MASK | FACILITY_SYSTEM_MASK | 0x00000011L ) )

#define STATUS_MORE_PROCESSING_REQUIRED         ( ( NTSTATUS )( STATUS_SEVERITY_INFORMATIONAL_MASK | FACILITY_SYSTEM_MASK | 0x00000000L ) )
#define STATUS_WAIT_INCOMPLETE                  ( ( NTSTATUS )( STATUS_SEVERITY_INFORMATIONAL_MASK | FACILITY_SYSTEM_MASK | 0x00000001L ) )


//
// Bugcheck exception code's
//

//
// "The system has pogged"
//

#define STATUS_ASSERTION_FAILURE                0x00000010
#define STATUS_UNSUPPORTED_PROCESSOR            0x00000011
#define STATUS_KERNEL_INITIALIZATION_FAILURE    0x00000012
#define STATUS_UNHANDLED_SYSTEM_EXCEPTION       0x00000013
#define STATUS_MEMORY_MANAGER                   0x00000014
#define STATUS_IRQL_NOT_LESS_THAN_OR_EQUAL      0x00000015
